function ownKeys(a,b){var c=Object.keys(a);if(Object.getOwnPropertySymbols){var d=Object.getOwnPropertySymbols(a);b&&(d=d.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));c.push.apply(c,d)}return c}
function _objectSpread(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{};b%2?ownKeys(Object(c),!0).forEach(function(b){_defineProperty(a,b,c[b])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(c)):ownKeys(Object(c)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(c,b))})}return a}
function _defineProperty(a,b,c){return(b=_toPropertyKey(b))in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}function _toPropertyKey(a){a=_toPrimitive(a,"string");return"symbol"==_typeof(a)?a:a+""}
function _toPrimitive(a,b){if("object"!=_typeof(a)||!a)return a;var c=a[Symbol.toPrimitive];if(void 0!==c){c=c.call(a,b||"default");if("object"!=_typeof(c))return c;throw new TypeError("@@toPrimitive must return a primitive value.");}return("string"===b?String:Number)(a)}
function _typeof(a){"@babel/helpers - typeof";return _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},_typeof(a)}
var ZSDKUtil=function(a){function b(a){}function c(a){var b={};a=a||window.location.href;a.substr(a.indexOf("?")+1).split("\x26").forEach(function(a,c){var d=a.split("\x3d");b[d[0]]=d[1]});b.hasOwnProperty("serviceOrigin")&&(b.serviceOrigin=decodeURIComponent(b.serviceOrigin));return b}var d=c(),h;b.prototype.Info=function(){(a.isDevMode()||a.isLogEnabled())&&window.console.info.apply(null,arguments)};b.prototype.Error=function(){(a.isDevMode()||a.isLogEnabled())&&window.console.error.apply(null,
arguments)};a.GetQueryParams=c;a.isDevMode=function(){return d&&d.isDevMode};a.isLogEnabled=function(){return d&&d.isLogEnabled};a.getLogger=function(){h&&h instanceof b||(h=new b);return h};a.Sleep=function(a){for(var b=(new Date).getTime();b+a>(new Date).getTime(););};return a}(window.ZSDKUtil||{}),ZSDKMessageManager=function(a){function b(e){try{var a="string"===typeof e.data?JSON.parse(e.data):e.data}catch(b){a=e.data}var f=a.type,k=a.eventName;try{var n;if(!(n="SET_CONTEXT"===k)){var m=e.source,
v=e.origin;n=p.isAppRegistered()&&q===m&&u===v?!0:Error("Un-Authorized Message.")}if(n)switch(f){case "FRAMEWORK.EVENT":var B={SET_CONTEXT:c,UPDATE_CONTEXT:d,EVENT_RESPONSE:h,EVENT_RESPONSE_FAILURE:g}[a.eventName];B&&"function"===typeof B?B(e,a):ZSDKEventManager.NotifyEventListeners(p.AppContext,a.eventName,a.data);break;default:p.MessageInterceptor(e,a)}}catch(b){r.Error("[SDK.MessageHandler] \x3d\x3e ",b.stack)}}function c(e,a){q=window.parent;u=p.QueryParams.serviceOrigin;p.SetContext(a.data);
p.ExecuteLoadHandler()}function d(e,a){}function h(e,a){k(a.promiseid,!0,a.data)}function g(e,a){k(a.promiseid,!1,a.data)}function k(a,b,c){e.hasOwnProperty(a)&&(b?e[a].resolve(c):e[a].reject(c),e[a]=void 0,delete e[a])}function m(a){return new Promise(function(b,c){e[a]={resolve:b,reject:c,time:(new Date).getTime()}})}function f(a){"object"===_typeof(a)&&(a.appOrigin=encodeURIComponent(n()));if(!q)throw Error("Parentwindow reference not found.");q.postMessage(a,p.QueryParams.serviceOrigin)}function n(){return window.location.protocol+
"//"+window.location.host+window.location.pathname}var p,r=ZSDKUtil.getLogger(),x=100,e={},q,u;a.Init=function(e,c){if(!e||"object"!==_typeof(e))throw Error("Invalid Context object passed");if(c&&"object"!==_typeof(c))throw Error("Invalid Configuration Passed to MessageManager");p=e;return b.bind(a)};a.RegisterApp=function(a){a=_objectSpread({type:"SDK.EVENT",eventName:"REGISTER",appOrigin:encodeURIComponent(n())},a);window.parent.postMessage(a,p.QueryParams.serviceOrigin)};a.DERegisterApp=function(){var a=
{type:"SDK.EVENT",eventName:"DEREGISTER",uniqueID:p.getUniqueID()};f(a)};a.SendRequest=function(a){if(!a||"object"!==_typeof(a))throw Error("Invalid Options passed");var e;e="Promise"+x++;a={type:"SDK.EVENT",eventName:"HTTP_REQUEST",uniqueID:p.getUniqueID(),time:(new Date).getTime(),promiseid:e,data:a};f(a);e=m(e);return e};a.TriggerEvent=function(a,e,b){if(!a)throw Error("Invalid Eventname : ",a);var c=b?"Promise"+x++:void 0;a={type:"SDK.EVENT",eventName:a,uniqueID:p.getUniqueID(),time:(new Date).getTime(),
promiseid:c,data:e};f(a);if(b)return m(c)};return a}(window.ZSDKMessageManager||{}),ZSDKEventManager=function(a){var b=ZSDKUtil.getLogger(),c={};a.AttachEventListener=function(a,b){"function"===typeof b&&(Array.isArray(c[a])||(c[a]=[]),c[a].push(b))};a.NotifyEventListeners=function(a,h,g){var k=h.match(/^\__[A-Za-z_]+\__$/gi);Array.isArray(k);if((k=c[h])&&Array.isArray(k))for(h=0;h<k.length;h++)k[h].call(a,g);else b.Info("Cannot find EventListeners for Event : ",h)};a.NotifyInternalEventHandler=function(a,
b){var c=b.eventName;"__APP_INIT__"===c?(a.SetContext(b.data),a.ExecuteLoadHandler()):"__APP_CONTEXT_UPDATE__"===c&&(a.UpdateContext(b.data),a.ExecuteContextUpdateHandler())};return a}(window.ZSDKEventManager||{});
function ZSDK(a){function b(){"function"!==typeof q?D.Error("No OnLoad Handler provided to execute."):v?D.Error("OnLoad event already triggered."):(q.call(l,l),v=!0)}function c(){u.call(l,l)}function d(){return y}function h(a,e,b){return ZSDKMessageManager.TriggerEvent(a,e,b)}function g(a){D.Info("Setting AppContext data");var e=a&&a.model||{};isDevMode&&a.locale&&a.localeResource&&0===Object.keys(a.localeResource).length&&a.localeResource.constructor===Object&&a.locale&&n(a.locale);if("undefined"!==
typeof ZSDKModelManager){for(var b in e)ZSDKModelManager.AddModel(b,e[b]);l.Model=ZSDKModelManager.GetModelStore()}t=a.uniqueID;A=a.connectors;D.Info("App Connectors ",A);y=!0}function k(){return t}function m(a){}function f(){return A}function n(a){p("/app-translations/"+a+".json",function(a){w=JSON.parse(a);e()})}function p(a,e){var b=new XMLHttpRequest;b.open("GET",a,!1);b.onreadystatechange=function(){4==b.readyState&&"200"==b.status&&e(b.responseText)};b.send(null)}function r(a,e,b){for(var c=
"";c!=a;)c=a,a=a.replace(e,b);return a}function x(a,e){e=e.replace(/\[(\w+)\]/g,".$1");e=e.replace(/^\./,"");for(var b=e.split("."),c=0,l=b.length;c<l;++c){var d=b[c];if(d in a)a=a[d];else return}return a}function e(){var a=document.querySelectorAll("[data-i18n]"),e;for(e in a)if(a.hasOwnProperty(e)){var b=x(w,a[e].getAttribute("data-i18n"));if(!b)return!1;if(a[e].hasAttribute("data-options")){var c=JSON.parse(JSON.stringify(eval("("+a[e].getAttribute("data-options")+")"))),l=Object.keys(c),d;for(d in l)b=
r(b,"${"+l[d]+"}",c[l[d]])}a[e].innerHTML=b}}var q,u,A,z,t,w={},D=ZSDKUtil.getLogger(),y=!1,v=!1,B=a.registrationMeta||{};this.isContextReady=!1;this.HelperContext={};this.isDevMode=!1;this.getContext=function(){return l};var l={Model:{},Event:{}};l.Event.Listen=function(a,e){ZSDKEventManager.AttachEventListener(a,e)};l.Event.Trigger=h;l.GetRequest=function(a){return ZSDKMessageManager.SendRequest(a)};l.QueryParams=z;l.Translate=function(a,e){var b="";a&&(b=x(w,a));if(!b)return!1;if(e){var c=JSON.parse(JSON.stringify(eval(e))),
l=Object.keys(c);for(a in l)b=r(b,"${"+l[a]+"}",c[l[a]])}return b};this.OnLoad=function(a){if("function"!==typeof a)throw Error("Invalid Function value is passed");q=a;y&&b()};this.OnUnLoad=function(a){};this.OnContextUpdate=function(a){u=a};(function(){z=ZSDKUtil.GetQueryParams();isDevMode=!!z.isDevMode;var a={};a.isDevMode=isDevMode;a.ExecuteLoadHandler=b;a.SetContext=g;a.UpdateContext=m;a.QueryParams=z;a.GetConnectors=f;a.TriggerEvent=h;a.ExecuteContextUpdateHandler=c;a.getUniqueID=k;a.isAppRegistered=
d;var e=ZSDKMessageManager.Init(a);window.addEventListener("message",e);window.addEventListener("unload",function(){ZSDKMessageManager.DERegisterApp()});"undefined"!==typeof ZSDKModelManager&&ZSDKModelManager.Init(a);ZSDKMessageManager.RegisterApp(B)})()}"use strict";var _excluded=["id","type","api_name"];
function _objectWithoutProperties(a,b){if(null==a)return{};var c,d,h=_objectWithoutPropertiesLoose(a,b);if(Object.getOwnPropertySymbols){var g=Object.getOwnPropertySymbols(a);for(d=0;d<g.length;d++)c=g[d],-1===b.indexOf(c)&&{}.propertyIsEnumerable.call(a,c)&&(h[c]=a[c])}return h}function _objectWithoutPropertiesLoose(a,b){if(null==a)return{};var c={},d;for(d in a)({}).hasOwnProperty.call(a,d)&&-1===b.indexOf(d)&&(c[d]=a[d]);return c}
function _regeneratorKeys(a){var b=Object(a),c=[],d;for(d in b)c.unshift(d);return function g(){for(;c.length;)if((d=c.pop())in b)return g.value=d,g.done=!1,g;return g.done=!0,g}}function _slicedToArray(a,b){return _arrayWithHoles(a)||_iterableToArrayLimit(a,b)||_unsupportedIterableToArray(a,b)||_nonIterableRest()}
function _nonIterableRest(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}
function _iterableToArrayLimit(a,b){var c=null==a?null:"undefined"!=typeof Symbol&&a[Symbol.iterator]||a["@@iterator"];if(null!=c){var d,h,g,k,m=[],f=!0,n=!1;try{if(g=(c=c.call(a)).next,0===b){if(Object(c)!==c)return;f=!1}else for(;!(f=(d=g.call(c)).done)&&(m.push(d.value),m.length!==b);f=!0);}catch(p){n=!0,h=p}finally{try{if(!f&&null!=c.return&&(k=c.return(),Object(k)!==k))return}finally{if(n)throw h;}}return m}}function _arrayWithHoles(a){if(Array.isArray(a))return a}
function _regenerator(){function a(a,e,c,d){e=Object.create((e&&e.prototype instanceof b?e:b).prototype);return _regeneratorDefine2(e,"_invoke",function(a,e,b){function c(a,e){f=a;q=e;for(k=0;!E&&B&&!b&&k<l.length;k++){var b,d=l[k],n=C.p,h=d[2];3<a?(b=h===e)&&(q=d[(f=d[4])?5:(f=3,3)],d[4]=d[5]=g):d[0]<=n&&((b=2>a&&n<d[1])?(f=0,C.v=e,C.n=d[1]):n<h&&(b=3>a||d[0]>e||e>h)&&(d[4]=a,d[5]=e,C.n=h,f=0))}if(b||1<a)return p;throw E=!0,e;}var d,f,q,B=0,l=b||[],E=!1,C={p:0,n:0,v:g,a:c,f:c.bind(g,4),d:function(a,
e){return d=a,f=0,q=g,C.n=e,p}};return function(b,l,n){if(1<B)throw TypeError("Generator is already running");E&&1===l&&c(l,n);f=l;for(q=n;(k=2>f?g:q)||!E;){d||(f?3>f?(1<f&&(C.n=-1),c(f,q)):C.n=q:C.v=q);try{if(B=2,d){if(f||(b="next"),k=d[b]){if(!(k=k.call(d,q)))throw TypeError("iterator result is not an object");if(!k.done)return k;q=k.value;2>f&&(f=0)}else 1===f&&(k=d.return)&&k.call(d),2>f&&(q=TypeError("The iterator does not provide a '"+b+"' method"),f=1);d=g}else if((k=(E=0>C.n)?q:a.call(e,C))!==
p)break}catch(h){d=g,f=1,q=h}finally{B=1}}return{value:k,done:E}}}(a,c,d),!0),e}function b(){}function c(){}function d(){}function h(a){return Object.setPrototypeOf?Object.setPrototypeOf(a,d):(a.__proto__=d,_regeneratorDefine2(a,n,"GeneratorFunction")),a.prototype=Object.create(r),a}var g,k,m="function"==typeof Symbol?Symbol:{},f=m.iterator||"@@iterator",n=m.toStringTag||"@@toStringTag",p={};k=Object.getPrototypeOf;var m=[][f]?k(k([][f]())):(_regeneratorDefine2(k={},f,function(){return this}),k),
r=d.prototype=b.prototype=Object.create(m);return c.prototype=d,_regeneratorDefine2(r,"constructor",d),_regeneratorDefine2(d,"constructor",c),c.displayName="GeneratorFunction",_regeneratorDefine2(d,n,"GeneratorFunction"),_regeneratorDefine2(r),_regeneratorDefine2(r,n,"Generator"),_regeneratorDefine2(r,f,function(){return this}),_regeneratorDefine2(r,"toString",function(){return"[object Generator]"}),(_regenerator=function(){return{w:a,m:h}})()}
function _regeneratorDefine2(a,b,c,d){var h=Object.defineProperty;try{h({},"",{})}catch(g){h=0}_regeneratorDefine2=function(a,b,c,d){function n(b,c){_regeneratorDefine2(a,b,function(a){return this._invoke(b,c,a)})}b?h?h(a,b,{value:c,enumerable:!d,configurable:!d,writable:!d}):a[b]=c:(n("next",0),n("throw",1),n("return",2))};_regeneratorDefine2(a,b,c,d)}
function _typeof(a){"@babel/helpers - typeof";return _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},_typeof(a)}
function _createForOfIteratorHelper(a,b){var c="undefined"!=typeof Symbol&&a[Symbol.iterator]||a["@@iterator"];if(!c){if(Array.isArray(a)||(c=_unsupportedIterableToArray(a))||b&&a&&"number"==typeof a.length){c&&(a=c);var d=0,h=function(){};return{s:h,n:function(){return d>=a.length?{done:!0}:{done:!1,value:a[d++]}},e:function(a){throw a;},f:h}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}var g,k=!0,m=!1;return{s:function(){c=c.call(a)},n:function(){var a=c.next();return k=a.done,a},e:function(a){m=!0;g=a},f:function(){try{k||null==c.return||c.return()}finally{if(m)throw g;}}}}
function _unsupportedIterableToArray(a,b){if(a){if("string"==typeof a)return _arrayLikeToArray(a,b);var c={}.toString.call(a).slice(8,-1);return"Object"===c&&a.constructor&&(c=a.constructor.name),"Map"===c||"Set"===c?Array.from(a):"Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c)?_arrayLikeToArray(a,b):void 0}}function _arrayLikeToArray(a,b){(null==b||b>a.length)&&(b=a.length);for(var c=0,d=Array(b);c<b;c++)d[c]=a[c];return d}
function _wrapNativeSuper(a){var b="function"==typeof Map?new Map:void 0;return _wrapNativeSuper=function(a){function d(){return _construct(a,arguments,_getPrototypeOf(this).constructor)}if(null===a||!_isNativeFunction(a))return a;if("function"!=typeof a)throw new TypeError("Super expression must either be null or a function");if(void 0!==b){if(b.has(a))return b.get(a);b.set(a,d)}return d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}}),_setPrototypeOf(d,
a)},_wrapNativeSuper(a)}function _construct(a,b,c){if(_isNativeReflectConstruct())return Reflect.construct.apply(null,arguments);var d=[null];d.push.apply(d,b);d=new (a.bind.apply(a,d));return c&&_setPrototypeOf(d,c.prototype),d}function _isNativeFunction(a){try{return-1!==Function.toString.call(a).indexOf("[native code]")}catch(b){return"function"==typeof a}}
function _callSuper(a,b,c){return b=_getPrototypeOf(b),_possibleConstructorReturn(a,_isNativeReflectConstruct()?Reflect.construct(b,c||[],_getPrototypeOf(a).constructor):b.apply(a,c))}function _possibleConstructorReturn(a,b){if(b&&("object"==_typeof(b)||"function"==typeof b))return b;if(void 0!==b)throw new TypeError("Derived constructors may only return object or undefined");return _assertThisInitialized(a)}
function _assertThisInitialized(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function _isNativeReflectConstruct(){try{var a=!Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}))}catch(b){}return(_isNativeReflectConstruct=function(){return!!a})()}
function _getPrototypeOf(a){return _getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf.bind():function(a){return a.__proto__||Object.getPrototypeOf(a)},_getPrototypeOf(a)}function _inherits(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});Object.defineProperty(a,"prototype",{writable:!1});b&&_setPrototypeOf(a,b)}
function _setPrototypeOf(a,b){return _setPrototypeOf=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(a,b){return a.__proto__=b,a},_setPrototypeOf(a,b)}function ownKeys(a,b){var c=Object.keys(a);if(Object.getOwnPropertySymbols){var d=Object.getOwnPropertySymbols(a);b&&(d=d.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));c.push.apply(c,d)}return c}
function _objectSpread(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{};b%2?ownKeys(Object(c),!0).forEach(function(b){_defineProperty(a,b,c[b])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(c)):ownKeys(Object(c)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(c,b))})}return a}
function _defineProperty(a,b,c){return(b=_toPropertyKey(b))in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}function _defineProperties(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,_toPropertyKey(d.key),d)}}
function _createClass(a,b,c){return b&&_defineProperties(a.prototype,b),c&&_defineProperties(a,c),Object.defineProperty(a,"prototype",{writable:!1}),a}function _toPropertyKey(a){a=_toPrimitive(a,"string");return"symbol"==_typeof(a)?a:a+""}
function _toPrimitive(a,b){if("object"!=_typeof(a)||!a)return a;var c=a[Symbol.toPrimitive];if(void 0!==c){c=c.call(a,b||"default");if("object"!=_typeof(c))return c;throw new TypeError("@@toPrimitive must return a primitive value.");}return("string"===b?String:Number)(a)}function _classPrivateMethodInitSpec(a,b){_checkPrivateRedeclaration(a,b);b.add(a)}function _classPrivateFieldInitSpec(a,b,c){_checkPrivateRedeclaration(a,b);b.set(a,c)}
function _checkPrivateRedeclaration(a,b){if(b.has(a))throw new TypeError("Cannot initialize the same private elements twice on an object");}function _classPrivateFieldGet(a,b){return a.get(_assertClassBrand(a,b))}function _classPrivateFieldSet(a,b,c){return a.set(_assertClassBrand(a,b),c),c}function _assertClassBrand(a,b,c){if("function"==typeof a?a===b:a.has(b))return 3>arguments.length?b:c;throw new TypeError("Private element is not present on this object");}
function asyncGeneratorStep(a,b,c,d,h,g,k){try{var m=a[g](k),f=m.value}catch(n){return void c(n)}m.done?b(f):Promise.resolve(f).then(d,h)}function _asyncToGenerator(a){return function(){var b=this,c=arguments;return new Promise(function(d,h){function g(a){asyncGeneratorStep(m,d,h,g,k,"next",a)}function k(a){asyncGeneratorStep(m,d,h,g,k,"throw",a)}var m=a.apply(b,c);g(void 0)})}}var __isInitTriggered=!1;
(function(){var a;self._getAppSDK=function(){a||(a=new ZSDK({registrationMeta:{sdkVersion:"1.5"}}));return a}})();
var ZOHO=function(){var a,b={},c=void 0;return{embeddedApp:{on:function(a,c){b[a]=c},init:function(){if(!__isInitTriggered){__isInitTriggered=!0;a=self._getAppSDK();var d;c=new Promise(function(a,b){d=a});a.OnLoad(function(){d()});for(var h in b)a.getContext().Event.Listen(h,b[h])}return c}},CRM:function(){function b(e){e.sdkVersion="1.5";return a.getContext().Event.Trigger("CRM_EVENT",e,!0)}function c(a){return new File([a],a.name,{type:a.type})}function g(a,f,n,g){if(f.FileData){var k=c(f.FileData);
f.FileData=k}a={category:"CREATE",Entity:a,RelatedID:n,APIData:f};a.type=g||"RECORD";return b(a)}function k(a){a.category="BLUEPRINT";return b(a)}function m(a){a.category="APPROVALS";return b(a)}function f(a,f,n){if(f.FILE){var g=c(f.FILE.file);f.FILE.file=g}g=void 0;if(n)g=f;else{var g=f.url,k=f.params,m=f.headers,p=f.body,r=f.PARTS,x=f.PART_BOUNDARY,v=f.CONTENT_TYPE,B=f.RESPONSE_TYPE;f=f.FILE;if(!g)throw{Message:"Url missing"};if(k){var l,E=[];for(l in k)E.push(encodeURIComponent(l)+"\x3d"+encodeURIComponent(k[l]));
l=E.join("\x26");g+=(-1<g.indexOf("?")?"\x26":"?")+l}g={url:g,Header:m,Body:p,CONTENT_TYPE:v,RESPONSE_TYPE:B,PARTS:r,PARTS_BOUNDARY:x,FILE:f}}return b({category:"CONNECTOR",nameSpace:a,data:g,type:n})}function n(a){a.category="UI";return b(a)}function p(a,c,f){return b({category:"CONFIG",type:a,nameSpace:c,APIData:f})}function r(a){var c={category:"USER"};a.ID?c.ID=a.ID:a.Type&&(c.Type=a.Type,a.page&&(c.page=a.page),a.per_page&&(c.per_page=a.per_page));return b(c)}function x(a){return b({category:"META",
type:a.type,Entity:a.Entity,Id:a.Id})}return{ACTION:{setConfig:function(a){return b({category:"ACTION",type:"CUSTOM_ACTION_SAVE_CONFIG",object:a})},enableAccountAccess:function(a){return b({category:"ACTION",type:"ENABLE_ACCOUNT_ACCESS",object:a})}},FUNCTIONS:{execute:function(a,c){var f={};c.auth_type="oauth";f.data=c;return b({category:"FUNCTIONS_EXECUTE",customFunctionName:a,data:f})}},EVENTS:{dispatch:function(a,c){return b({category:"EVENTS_DISPATCH",event_name:a,event_data:c})}},CONFIG:{getOrgInfo:function(a){return p("ORG")},
getCurrentUser:function(){return p("CURRENT_USER")},GetCurrentEnvironment:function(){return p("ORG_LEVEL_INFO")},getUserPreference:function(){return p("USER_PREFERENCE")}},META:{getFields:function(a){a.type="FIELD_LIST";return x(a)},getModules:function(){return x({type:"MODULE_LIST"})},getAssignmentRules:function(a){a.type="ASSIGNMENT_RULES";return x(a)},getLayouts:function(a){a.id=a.id?a.id:a.LayoutId;a.type=a.Id?"LAYOUT":"LAYOUTS";return x(a)},getRelatedList:function(a){a.type="RELATED_LIST";return x(a)},
getCustomViews:function(a){a.type=a.Id?"CUSTOM_VIEW":"CUSTOM_VIEWS";return x(a)}},API:{addNotes:function(a){return g(a.Entity,{data:[{Note_Title:a.Title,Note_Content:a.Content}]},a.RecordID,"NOTES")},addNotesAttachment:function(a){return b({category:"UPDATE",type:"NOTES",Entity:a.Entity,RecordID:a.RecordID,RelatedRecordID:a.RelatedRecordID,APIData:{Files:{FileName:File.Name,FileData:File.Content}}})},coql:function(a){return b({category:"QUERY",APIData:a})},insertRecord:function(a){var b=a.Entity,
c=a.APIData;c.trigger=a.Trigger;return g(b,c)},upsertRecord:function(a){var b=a.Entity,c=a.APIData;c.trigger=a.Trigger;c.action="UPSERT";a.duplicate_check_fields&&a.duplicate_check_fields instanceof Array&&(c.duplicate_check_fields=a.duplicate_check_fields.join(","));return g(b,c)},getRecord:function(a){return b({category:"READ",APIData:a})},getBluePrint:function(a){return k({Entity:a.Entity,RecordID:a.RecordID,action:"GET_BLUEPRINT_STATUS"})},updateBluePrint:function(a){return k({Entity:a.Entity,
RecordID:a.RecordID,BlueprintData:a.BlueprintData,action:"UPDATE_BLUEPRINT_STATUS"})},uploadFile:function(a){if(a.FILE){var f=c(a.FILE.file);a.FILE.file=f}return b({FileData:a,category:"FILES",type:"UPLOAD_FILE"})},getFile:function(a){a.category="FILES";a.type="DOWNLOAD_FILE";return b(a)},getAllRecords:function(a){return b({category:"READ",APIData:a})},updateRecord:function(a){var c=a.Entity,f=a.APIData;f.trigger=a.Trigger;return b({category:"UPDATE",type:"RECORD",Entity:c,APIData:f})},deleteRecord:function(a){return b({category:"DELETE",
type:"RECORD",Entity:a.Entity,RecordID:a.RecordID})},searchRecord:function(a){return b({category:"SEARCH",Entity:a.Entity,Type:a.Type,Query:a.Query,page:a.page,per_page:a.per_page,delay:a.delay})},getAllActions:function(a){a.action="GET_ALL_ACTIONS";return m(a)},getApprovalRecords:function(a){var b={};a?a.action="GET_APPROVAL_RECORDS":(b.action="GET_APPROVAL_RECORDS",a=b);return m(a)},getApprovalById:function(a){a.action="GET_APPROVALBYID";return m(a)},getApprovalsHistory:function(){return m({action:"GET_APPROVALS_HISTORY"})},
approveRecord:function(a){a.action="UPDATE_APPROVAL";return m(a)},getAllUsers:function(a){return r({Type:a.Type,page:a.page,per_page:a.per_page})},getUser:function(a){return r({ID:a.ID})},getRelatedRecords:function(a){return b({category:"READ",APIData:a})},updateRelatedRecords:function(a){return b({category:"UPDATE",type:"RELATED_RECORD",Entity:a.Entity,RecordID:a.RecordID,RelatedList:a.RelatedList,RelatedRecordID:a.RelatedRecordID,APIData:a.APIData})},delinkRelatedRecord:function(a){return b({category:"DELETE",
type:"RELATED_RECORD",Entity:a.Entity,RecordID:a.RecordID,RelatedList:a.RelatedList,RelatedRecordID:a.RelatedRecordID})},attachFile:function(a){var b=a.Entity,c=a.RecordID;a=a.File;a={FileName:a.Name,FileData:a.Content};return g(b,a,c,"ATTACHMENT")},getAllProfiles:function(a){return b({category:"PROFILES",type:"GET_ALL_PROFILES"})},getProfile:function(a){return b({category:"PROFILES",type:"GET_PROFILE",ID:a.ID})},updateProfile:function(a){return b({category:"UPDATE",type:"PROFILE",ID:a.ID,APIData:a.APIData})},
getOrgVariable:function(a){return p("VARIABLE",a)}},UI:{Resize:function(a){a={action:"RESIZE",data:{width:a.width,height:a.height}};return n(a)},Dialer:{maximize:function(){return n({action:{telephony:"MAXIMIZE"}})},minimize:function(){return n({action:{telephony:"MINIMIZE"}})},notify:function(){return n({action:{telephony:"NOTIFY"}})}},Record:{open:function(a){a={action:{record:"OPEN"},data:{Entity:a.Entity,RecordID:a.RecordID,target:a.Target}};return n(a)},edit:function(a){a={action:{record:"EDIT"},
data:{Entity:a.Entity,RecordID:a.RecordID,target:a.Target}};return n(a)},create:function(a){a={action:{record:"CREATE"},data:{Entity:a.Entity,RecordID:a.RecordID,target:a.Target}};return n(a)},populate:function(a){return n({action:{record:"POPULATE"},data:a})}},Popup:{close:function(){return n({action:{popup:"CLOSE"}})},closeReload:function(){return n({action:{popup:"CLOSE_RELOAD"}})}},Widget:{open:function(a){a={action:{webTab:"OPEN"},data:a};return n(a)}}},HTTP:{get:function(a){return f("wget.get",
a)},post:function(a){return f("wget.post",a)},put:function(a){return f("wget.put",a)},patch:function(a){return f("wget.patch",a)},delete:function(a){return f("wget.delete",a)}},CONNECTOR:{invokeAPI:function(a,b){return f(a,b,"CONNECTOR_API")},authorize:function(a){return f(a,{},"CONNECTOR_AUTHORIZE")}},CONNECTION:{invoke:function(a,c){var f={},g={};g.url=c.url;g.method=c.method;g.param_type=c.param_type;g.parameters=JSON.stringify(c.parameters);g.headers=JSON.stringify(c.headers);f.data=g;return b({category:"CRM_CONNECTION",
connectionName:a,data:f})}},WIZARD:{post:function(a){a={category:"CRM_WIZARD",data:JSON.stringify(a)};return b(a)}},BLUEPRINT:{proceed:function(){return b({category:"CRM_BLUEPRINT"})}}}}()}}();
(function(){function a(a){a.zrcVersion="1.0";a.sdkVersion="1.5";if(self.__isInitTriggered)return p||(p=self._getAppSDK()),p.getContext().Event.Trigger("CRM_EVENT",a,!0);console.error(new w("ZRC methods called before init"))}function b(){return c.apply(this,arguments)}function c(){c=_asyncToGenerator(_regenerator().m(function l(){var b;return _regenerator().w(function(c){for(;;)switch(c.n){case 0:b=null;if(!r){c.n=1;break}return c.a(2,r);case 1:return c.n=2,a({category:"GET_PARENT_URL"});case 2:if(b=
c.v){c.n=3;break}throw new w("Failed to get current page url for your zrc request");case 3:return r=new URL(b),c.a(2,r)}},l)}));return c.apply(this,arguments)}function d(a){var b;switch(a.errorType){case "ConnectionError":b=new y(a.errorMessage?a.errorMessage:"Connection request failed");break;case "ZrcValidationError":b=new t(a.errorMessage);break;case "ZrcError":b=new w(a.errorMessage);break;case "ApiError":b=new D(a.errorMessage);break;case "PermissionException":b=Error(a.errorMessage);b.code=
a.errorCode;b.detail=a.errorDetail;b.type=a.errorType;break;default:b=new w(a.errorMessage)}return b}function h(a){return g.apply(this,arguments)}function g(){g=_asyncToGenerator(_regenerator().m(function l(c){var f,e,g,n,k,h,m,p,r,q,v=arguments,t;return _regenerator().w(function(l){for(;;)switch(l.p=l.n){case 0:f=1<v.length&&void 0!==v[1]?v[1]:{};if(e=2<v.length&&void 0!==v[2]?v[2]:void 0){l.n=2;break}l.n=1;return b();case 1:e=l.v;case 2:l.p=2;g={category:"ZRC_REQUEST",url:c,options:{}};if(f.body&&
f.body instanceof FormData){n={};k=_createForOfIteratorHelper(f.body.entries());try{for(k.s();!(h=k.n()).done;)m=_slicedToArray(h.value,2),p=m[0],r=m[1],n[p]=r instanceof File?r:r.toString()}catch(u){k.e(u)}finally{k.f()}f.body=n;g.options.bodyDataType="formData"}g.requestConfig=f;q=a(g);return l.a(2,q.then(function(a){return a}).catch(function(a){a&&a.errorType&&"string"===typeof a.errorType&&(a=d(a));a.error&&a.error.errorType&&"string"===typeof a.error.errorType&&(a.error=d(a.error));throw a;}));
case 3:throw l.p=3,t=l.v,t;case 4:return l.a(2)}},l,null,[[2,3]])}));return g.apply(this,arguments)}function k(a,b,c,f){return m.apply(this,arguments)}function m(){m=_asyncToGenerator(_regenerator().m(function l(a,b,c,d){var g,k,h,m,p,r,t,u,z,w,A,D,y,F,G,H,I,J;return _regenerator().w(function(l){for(;;)switch(l.n){case 0:d&&(delete d.method,delete d.body);_classPrivateFieldGet(q,this).body&&(c=c?c:_classPrivateFieldGet(q,this).body);d=_objectSpread(_objectSpread({},_classPrivateFieldGet(q,this)),
d);v.validateConfig(b,d);["GET","OPTIONS","HEAD"].includes(a.toUpperCase())&&c&&(c=void 0);d&&d.headers&&(p=Object.keys(d.headers).reduce(function(a,b){a[b.toLowerCase()]=d.headers[b];return a},{}),d.headers=p);d||(d={headers:{}});if("POST"===a||"PUT"===a||"PATCH"===a||"DELETE"===a)d.headers||(d.headers={}),!d.headers["content-type"]&&c&&(v.isJsonObject(c)||v.isJsonString(c))&&(d.headers["content-type"]="application/json");d&&d.headers&&(d.headers=n(d.headers,c));c&&null!==(g=d)&&void 0!==g&&g.headers&&
null!==(k=d.headers["content-type"])&&void 0!==k&&k.trim().startsWith("application/json")&&(c=v.isJsonString(c)?c:v.isJsonObject(c)?JSON.stringify(c):c);if(H=(null===(h=d)||void 0===h?void 0:h.baseUrl)||(null===(m=_classPrivateFieldGet(q,this))||void 0===m?void 0:m.baseUrl)){l.n=2;break}l.n=1;return _classPrivateFieldGet(e,this).call(this);case 1:H=l.v.origin;case 2:r=H;t=v.isRelativePath(b)?f(b,r):new URL(b);if(!(d&&d.params&&0<Object.keys(d.params).length)){l.n=8;break}u=t.searchParams;I=_regeneratorKeys(d.params);
case 3:if((J=I()).done){l.n=8;break}z=J.value;w=d.params[z];if(null!==w&&void 0!==w){l.n=4;break}return l.a(3,3);case 4:if(!Array.isArray(w)){l.n=6;break}if(0!==w.length){l.n=5;break}return l.a(3,3);case 5:A=_createForOfIteratorHelper(w);try{for(A.s();!(D=A.n()).done;)y=D.value,null!==y&&void 0!==y&&(F="".concat(z,"[]"),y instanceof Date?u.append(F,y.toISOString()):v.isJsonObject(y)?u.append(F,JSON.stringify(y)):u.append(F,y))}catch(K){A.e(K)}finally{A.f()}l.n=7;break;case 6:w instanceof Date?u.append(z,
w.toISOString()):v.isJsonObject(w)?u.append(z,JSON.stringify(w)):u.append(z,w);case 7:l.n=3;break;case 8:return G=_objectSpread({method:a},d),c&&(G.body=c),"GET"===a&&delete G.body,l.a(2,_classPrivateFieldGet(x,this).call(this,t.toString(),G))}},l,this)}));return m.apply(this,arguments)}function f(a,b){b&&(b=b.endsWith("/")?b.slice(0,-1):b);a=a.startsWith("/")?a.slice(1):a;return b?new URL("".concat(b,"/").concat(a)):new URL(a)}function n(a,b){if(b instanceof FormData||b instanceof URLSearchParams||
b instanceof Blob||b instanceof File||b instanceof ReadableStream){var c=JSON.parse(JSON.stringify(a));delete c["content-type"];return c}return a}var p,r=null,x=new WeakMap,e=new WeakMap,q=new WeakMap,u=new WeakSet,A=function(){function a(c){_classCallCheck(this,a);_classPrivateMethodInitSpec(this,u);_classPrivateFieldInitSpec(this,x,h);_classPrivateFieldInitSpec(this,e,b);_classPrivateFieldInitSpec(this,q,{headers:{}});c&&_classPrivateFieldSet(q,this,_objectSpread(_objectSpread({},_classPrivateFieldGet(q,
this)),c))}return _createClass(a,[{key:"get",value:function(a,b){return _assertClassBrand(u,this,k).call(this,"GET",a,void 0,b)}},{key:"post",value:function(a,b,c){return _assertClassBrand(u,this,k).call(this,"POST",a,b,c)}},{key:"put",value:function(a,b,c){return _assertClassBrand(u,this,k).call(this,"PUT",a,b,c)}},{key:"patch",value:function(a,b,c){return _assertClassBrand(u,this,k).call(this,"PATCH",a,b,c)}},{key:"delete",value:function(a,b){return _assertClassBrand(u,this,k).call(this,"DELETE",
a,void 0,b)}},{key:"options",value:function(a,b){return _assertClassBrand(u,this,k).call(this,"OPTIONS",a,void 0,b)}},{key:"head",value:function(a,b){return _assertClassBrand(u,this,k).call(this,"HEAD",a,void 0,b)}},{key:"request",value:function(a){if(!a||!v.isJsonObject(a))throw new t("Invalid requestConfig provided for zrc.request method");a.method=a.method||"GET";var b=a.path,c=a.body,b=b||"/";delete a.path;delete a.body;return _assertClassBrand(u,this,k).call(this,a.method.toUpperCase(),b,c,a)}},
{key:"createInstance",value:function(a){if(!a||!v.isJsonObject(a))throw new t("Invalid ZrcRequestConfig provided for zrc.createInstance method");a&&(delete a.method,delete a.body);return new z(a)}}])}(),z=function(a){function b(){_classCallCheck(this,b);return _callSuper(this,b,arguments)}_inherits(b,a);return _createClass(b,[{key:"createInstance",value:function(){throw new t("createInstance method is not supported in Custom ZRC object");}}])}(A),t=function(a){function b(a){var c;_classCallCheck(this,
b);c=_callSuper(this,b);_defineProperty(c,"name",void 0);_defineProperty(c,"message",void 0);_defineProperty(c,"stack",void 0);c.name="ZRC_VALIDATION_FAILED_ERROR";c.message=a?a:"validation failed with your zrc request";delete c.stack;return c}_inherits(b,a);return _createClass(b)}(_wrapNativeSuper(Error)),w=function(a){function b(a){var c;_classCallCheck(this,b);c=_callSuper(this,b);_defineProperty(c,"name",void 0);_defineProperty(c,"message",void 0);_defineProperty(c,"stack",void 0);c.name="ZRC_ERROR";
c.message=a?a:"something went wrong while setting up your zrc request";delete c.stack;return c}_inherits(b,a);return _createClass(b)}(_wrapNativeSuper(Error)),D=function(a){function b(a){var c;_classCallCheck(this,b);c=_callSuper(this,b);_defineProperty(c,"name",void 0);_defineProperty(c,"message",void 0);_defineProperty(c,"stack",void 0);c.name="API_ERROR";c.message=a?a:"Your API request has failed";delete c.stack;return c}_inherits(b,a);return _createClass(b)}(_wrapNativeSuper(Error)),y=function(a){function b(a){var c;
_classCallCheck(this,b);c=_callSuper(this,b);_defineProperty(c,"name",void 0);_defineProperty(c,"message",void 0);_defineProperty(c,"stack",void 0);c.name="CONNECTION_ERROR";c.message=a?a:"Connection Error";delete c.stack;return c}_inherits(b,a);return _createClass(b)}(_wrapNativeSuper(Error)),v=function(){function a(){_classCallCheck(this,a)}return _createClass(a,null,[{key:"validateConfig",value:function(b){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};if(!b||"string"!==typeof b||
""===b.trim())throw new t("Invalid path provided for zrc request: '".concat(b,"'"));c.responseType&&a.validateResponseType(c.responseType);a.validateRequestConfigProperties(c);if(!a.isRelativePath(b)){if(!a.isValidUrl(b))throw new t("Invalid 'path' provided, please provide a relative-path or a valid absolute url for zrc requests: ".concat(b));if(c.baseUrl)throw new t("No need to provide 'baseUrl' when absolute url provided in path. Please remove the baseUrl: ".concat(c.baseUrl));}else if(c.connection&&
(!c.baseUrl||"string"!==typeof c.baseUrl||""===c.baseUrl.trim()))throw new t("Please provide a valid 'baseUrl' or provide absolute url in 'path' for zrc connection requests");}},{key:"validateResponseType",value:function(b){if(b){if(!a.isAllowedResponseType(b))throw new t("Unsupported responseType: '".concat(b,"' provided in requestConfig"));switch(b){case "blob":if("undefined"===typeof self)throw new t("ResponseType 'blob' is only supported in browsers");}}}},{key:"validateRequestConfigProperties",
value:function(a){for(var b="connection method headers signal mode cache referrerPolicy responseType baseUrl params handleUserConnectionAuth".split(" "),c=0,d=Object.keys(a);c<d.length;c++){var f=d[c];if(!b.includes(f))throw new t("The property '".concat(f,"' is not allowed in requestConfig."));}if(void 0!==a.connection){if("string"!==typeof a.connection||""===a.connection.trim())throw new t("Invalid value provided for property 'connection' in requestConfig: '".concat(a.connection,"'"));if(a.connection){var b=
new Set("authorization url connection-details cookie connection waf-encryption-key waf-encryption-id zsec_user_import_url zsec_proxy_server_name zsec_proxy_server_signature zsec_proxy_request zs-systemauthorization x-http-method-override x-zcsrf-token user-agent remote_user_ip req-mi-chain host".split(" ")),c=["x-crm-","x-zcsrf","x-zoho","x-zohocrm","lb_"],e;for(e in a.headers){if(b.has(e.toLowerCase()))throw new t("Header '".concat(e,"' is not allowed for connection requests"));a=_createForOfIteratorHelper(c);
var g;try{for(a.s();!(g=a.n()).done;){var n=g.value;if(e.toLowerCase().startsWith(n))throw new t("Header '".concat(e,"' is not allowed for connection requests"));}}catch(k){a.e(k)}finally{a.f()}}}}}},{key:"isRelativePath",value:function(a){try{return new URL(a),!1}catch(b){return!(a.startsWith("http://")||a.startsWith("https://")||!a.startsWith("/"))}}},{key:"isValidUrl",value:function(a){try{return new URL(a),!0}catch(b){return!1}}},{key:"isAllowedResponseType",value:function(a){return["json","text",
"blob","arraybuffer"].includes(a)}},{key:"isJsonString",value:function(a){try{return JSON.parse(a),!0}catch(b){return!1}}},{key:"isJsonObject",value:function(a){if(null===a||"object"!==_typeof(a)||a instanceof FormData||a instanceof Blob||a instanceof ArrayBuffer||a instanceof URLSearchParams)return!1;try{return JSON.stringify(a),!0}catch(b){return!1}}},{key:"validateCrmApiVersion",value:function(a){if(a.startsWith("/crm/")){if(a.startsWith("/crm/v")){var b=a.split("/")[2];if(7>parseInt(b.split("v")[1]))throw new t("zrc only supports v7 and above for CRM requests. Please provide valid version in path: '".concat(a,
"'"));}if(a.startsWith("/crm/bulk/v")||a.startsWith("/crm/email/v"))if(b=a.split("/")[3],7>parseInt(b.split("v")[1]))throw new t("zrc only supports v7 and above for CRM requests. Please provide valid version for path: '".concat(a,"'"));}}}])}();self.zrcInstance=new A;self.ZrcValidationError=t})();
var zrc=function(){var a=self.zrcInstance,b=self.ZrcValidationError;return{get:function(b,d){return a.get.call(a,b,d)},post:function(b,d,h){return a.post.call(a,b,d,h)},put:function(b,d,h){return a.put.call(a,b,d,h)},patch:function(b,d,h){return a.patch.call(a,b,d,h)},delete:function(b,d){return a.delete.call(a,b,d)},options:function(b,d){return a.options.call(a,b,d)},head:function(b,d){return a.head.call(a,b,d)},request:function(b){return a.request.call(a,b)},createInstance:function(c){if(!c)throw new b("requestConfig is required for zrc.createInstance method");
return a.createInstance.call(a,c)}}}();
(function(a){function b(a){a.sdkVersion="1.5";if(self.__isInitTriggered)return c||(c=self._getAppSDK()),c.getContext().Event.Trigger("ZDK_EVENT",a,!0);console.error(Error("ZDK methods called before init"))}var c,d={Client:function(){return{sendResponse:function(a,c){return b({action:"notify_response",message:{data:c,uuid:a}})},notify:function(a,c){return b({action:"notify",type:a,data:c})},showMessage:function(){var a=_asyncToGenerator(_regenerator().m(function m(a,c){return _regenerator().w(function(d){for(;;)switch(d.n){case 0:if(!("string"===
typeof a||a instanceof String)){d.n=1;break}return d.a(2,b({action:"msg_band",type:c&&c.type?c.type:"info",message:a}));case 1:throw new TypeError("First argument must be a String");case 2:return d.a(2)}},m)}));return function(b,c){return a.apply(this,arguments)}}(),showConfirmation:function(){var a=_asyncToGenerator(_regenerator().m(function m(a,c,d){return _regenerator().w(function(g){for(;;)switch(g.n){case 0:if(!("string"===typeof a||a instanceof String)){g.n=1;break}return g.a(2,b({action:"confirm",
accept_message:c,reject_message:d,acceptMsg:c,rejectMsg:d,message:a},{userInput:!0}));case 1:throw new TypeError("First argument must be a String");case 2:return g.a(2)}},m)}));return function(b,c,d){return a.apply(this,arguments)}}(),showAlert:function(){var a=_asyncToGenerator(_regenerator().m(function m(a,c,d){return _regenerator().w(function(g){for(;;)switch(g.n){case 0:if(!("string"===typeof a||a instanceof String)){g.n=1;break}return g.a(2,b({action:"alert",message:a,heading:c,accept_message:d},
{userInput:!0}));case 1:throw new TypeError("First argument must be a String");case 2:return g.a(2)}},m)}));return function(b,c,d){return a.apply(this,arguments)}}(),getInput:function(){var a=_asyncToGenerator(_regenerator().m(function m(a,c,d,g){var h;return _regenerator().w(function(e){for(;;)switch(e.n){case 0:if(!a){e.n=3;break}if(Array.isArray(a)){e.n=1;break}throw new TypeError("options should be an array");case 1:if(!(7<a.length)){e.n=2;break}throw Error("Max input limit of 7 reached");case 2:a.forEach(function(a){var b=
a.type,c=a.label,d=a.default_value,f=a.list_options;if(!["text","number","textarea","picklist","multiselectpicklist"].includes(b))throw new TypeError("unsupported field type : ".concat(b));if(c){if("string"!==typeof c)throw new TypeError("label can only be string: ".concat(c));if(30<c.length)throw Error("label must be atmost 30 characters: ".concat(c));}if(["picklist","multiselectpicklist"].includes(b)&&(!f||0===f.length))throw Error("The ".concat(b," does not contain any options"));if("string"===
typeof d&&(""===d||d&&0===d.trim().length)||d&&"Array"===typeof d&&0===d.length)throw Error("default value cannot be empty");var e={text:120,number:50,textarea:2E3,picklist:120,multiselectpicklist:120}[b];if(d){if("multiselectpicklist"===b){if(!Array.isArray(d))throw new TypeError("default_value can only be an Array for multiselectpicklist. Provided: '".concat(d,"'"));}else if("string"!==typeof d)throw new TypeError("default_value can only be string: ".concat(d));if(!["picklist","multiselectpicklist"].includes(b)&&
d.length>e)throw Error("default_value must be atmost ".concat(e," characters for ").concat(b," field"));if("picklist"===b){if(!f.some(function(a){return a.actual_value===d}))throw Error("provided default_value: '".concat(d,"' did not match with any of the actual values in the list of options"));}else"multiselectpicklist"===b&&d.forEach(function(a){if(!f.some(function(b){return b.actual_value===a}))throw Error("provided default_value: '".concat(a,"' did not match with any of the actual values in the list of options"));
})}if(f){if(!Array.isArray(f))throw Error("list_options should be an array");if(2E3<f.length)throw Error("list_options can have atmost 2000 options");var g=new Set,h=new Set;f.forEach(function(a){if(a.hasOwnProperty("actual_value")&&a.hasOwnProperty("display_value")){var b=a.actual_value;a=a.display_value;var c=b.length>e&&b||a.length>e&&a;if(c)throw Error("Each options in list_options must be atmost '".concat(e,"' characters. Option: '").concat(c,"' exceeds the limit"));if(""===b||0===b.trim().length)throw Error("actual_value in list_options can't be empty");
if(""===a||0===a.trim().length)throw Error("display_value in list_options can't be empty");if(g.has(b))throw Error("duplicate actual_value: '".concat(b,"' found in list_options"));if(h.has(a))throw Error("duplicate display_value: '".concat(a,"' found in list_options"));g.add(b);h.add(a)}else throw Error("each option in list_options must contain actual_value and display_value. list_option: ".concat(JSON.stringify(a)," is invalid"));})}});case 3:h=d&&40<d.length;if(!(g&&40<g.length||h)){e.n=4;break}throw Error("".concat(h?
"accept_message":"reject_message"," must be atmost 40 characters"));case 4:return e.a(2,b({action:"get_input",options:a,accept_message:d,reject_message:g,heading:c},{userInput:!0}))}},m)}));return function(b,c,d,h){return a.apply(this,arguments)}}(),openPopup:function(){var a=_asyncToGenerator(_regenerator().m(function m(a,c){var d,g,h,e;return _regenerator().w(function(m){for(;;)switch(m.n){case 0:d=a.id;g=a.type;h=a.api_name;e=_objectWithoutProperties(a,_excluded);if("widget"===g||"crux"===g||"slyteui"==
g){m.n=1;break}throw Error("unsupported popup type: ".concat(g));case 1:if("crux"!==g||["record_create","record_edit","record_detail","record_clone"].includes(h)){m.n=2;break}throw Error("unsupported crux type: ".concat(h));case 2:if("slyteui"!==g||"object"!=_typeof(c)||!Array.isArray(c.data)&&"object"===_typeof(c.data)){m.n=3;break}throw new TypeError("data must be a JSON object for slyteui type");case 3:e.offset=Object.assign({top:"0px",left:"center"},Object.fromEntries(Object.entries(e).filter(function(a){return["top",
"bottom","left","right"].includes(a[0])})));if(!e.animation_type||-1!=[1,2,3,4,5,6].indexOf(e.animation_type)){m.n=4;break}throw new TypeError("animation type should be in (1,2,3,4,5,6)");case 4:if(!(e.header&&50<e.header.length)){m.n=5;break}throw Error("header must be atmost 50 characters");case 5:return m.a(2,b({action:"open_widget_by_id",id:d,type:g,api_name:h,data:c,config:e},{userInput:!0}))}},m)}));return function(b,c){return a.apply(this,arguments)}}(),showLoader:function(){var a=_asyncToGenerator(_regenerator().m(function m(a){return _regenerator().w(function(c){for(;;)switch(c.n){case 0:a=
a||{type:"page",template:"standard"};if(!(""===a.template||a.template&&0===a.template.trim().length)){c.n=1;break}throw Error("Invalid Loader Template");case 1:if(""!==a.type||0!==a.type.trim().length){c.n=2;break}throw Error("Invalid Loader Type");case 2:a.type=a.type||(a.type="page");a.template=a.template||("page"===a.type?"standard":"spinner");if(["page"].includes(a.type)){c.n=3;break}throw new TypeError("Invalid Loader Type");case 3:if("page"===a.type&&["spinner","vertical-bar","standard","dot-spinner"].includes(a.template)){c.n=
4;break}throw Error("Invalid Loader Template");case 4:if(!(a.message&&240<a.message.length)){c.n=5;break}throw Error("Loader message must be atmost 240 characters");case 5:return c.a(2,b({action:"show_loader",type:a.type,template:a.template,message:a&&a.message?a.message:""},{loading:"page"===a.type&&"standard"!==a.template}))}},m)}));return function(b){return a.apply(this,arguments)}}(),hideLoader:function(){return b({action:"hide_loader"},{loading:!1})}}}()},h=function(){return{close:function(a){return b({action:"close_widget",
response:a},!0)}}}();a.ZDK=d;a.$Client=h})("undefined"!==typeof self?self:window);